### ISSUE TITLE
Clear Clipboard function

### ISSUE THREAD

**Issue by CMiksche** [codingmatty/cerebro-plugin-clipboard#1]
Hello,

a simple function to clear the clipboard history would be nice.

It could be activated by entering "clear clipboard" in Cerebro.

**Comment by codingmatty** [comment]
Just saw this mentioned in [this issue](https://github.com/KELiON/cerebro/issues/166) as well. Definitely next up 👍

**Comment by codingmatty** [comment]
This is fixed with v1.2.1
Use the following to clear clipboard history, as well as the current clipboard item (I could fix that part if that's not exactly the functionality we want): `clipboard clear`

**Comment by CMiksche** [comment]
Thanks. That's exactly what i want ;-)

**Comment by dharmeshkakadia** [comment]
Ia it possible to selectively remove items from the history ?

**Comment by codingmatty** [comment]
Sure. That shouldn't be too hard.

I could try to make it a button in the preview portion. Maaaybe using the
delete key when you are on the item that you want to delete..

**Comment by dharmeshkakadia** [comment]
That would help removing sensitive info from the history :)
