### ISSUE TITLE
Implement snippets

### ISSUE THREAD

**Issue by rapcal** [codingmatty/cerebro-plugin-clipboard#5]
The idea here is to mimic Alfred's snippet feature.

Implementation would [make clipboard items saveable](https://github.com/codingmatty/cerebro-plugin-clipboard/issues/3#issuecomment-286909083) and possibly re-callable via keywords.

**Comment by puyt** [comment]
I came across this issue when going through some of the available Cerebro plugins and by coincidence I released a snippet plugin recently, maybe it can be useful for you.

https://github.com/puyt/cerebro-snippets

**Comment by rapcal** [comment]
Thanks, @puyt! Seems fantastic :-D

**Comment by puyt** [comment]
@rapcal Thanks 😄 Any suggestions/improvements are always welcome.

I'll try to play around with the new plugin settings option in the next week to make some things customizable such as the highlight theme or font-size.
